#!/usr/bin/env bash

poetry=$(which poetry)
curr_dir=$(dirname "$0")

crontab -l | { cat; echo "0 9 * * 1,5 cd $curr_dir && $poetry run python3 backup-weekly-playlists.py >> cron-log.log 2>&1"; } | crontab -

